
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 15 16:20:00 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int CHAR = 49;
  public static final int CONST = 7;
  public static final int GRT = 27;
  public static final int LPAREN = 39;
  public static final int SEMI = 35;
  public static final int CONTINUE = 16;
  public static final int LST = 29;
  public static final int MINUS = 20;
  public static final int RPAREN = 40;
  public static final int LS = 28;
  public static final int BOOL = 50;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int INC = 33;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ASSIGN = 32;
  public static final int IF = 8;
  public static final int THIS = 17;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int LAND = 30;
  public static final int RETURN = 14;
  public static final int RBRACKET = 42;
  public static final int LAMBDA = 45;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int LOR = 31;
  public static final int NUMBER = 48;
  public static final int MOD = 23;
  public static final int NEQ = 25;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 46;
  public static final int EQ = 24;
  public static final int COLON = 36;
  public static final int FOREACH = 18;
  public static final int LBRACE = 43;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int DEC = 34;
  public static final int GR = 26;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

